CREATE SCHEMA IF NOT EXISTS ORCHESTRATION;
CREATE OR ALTER TABLE ORCHESTRATION.CONNECTIONCONTROLTABLE (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order COMMENT 'identity',
    CONNECTIONSETTING VARCHAR(100) NOT NULL,
	SNOWFLAKEACCOUNT VARCHAR(100) NOT NULL,
	SNOWFLAKEDATABASE VARCHAR(100) NOT NULL,
	SNOWFLAKEWAREHOUSE VARCHAR(100) NOT NULL,
    SNOWFLAKEUSER VARCHAR(100) NOT NULL,
    SNOWFLAKEPASSWORDSECRET VARCHAR(100) NOT NULL,
	SNOWFLAKEROLE VARCHAR(100) NOT NULL,
    UPDATEDATETIMEUTC VARCHAR(19) NOT NULL,
    constraint ORCHESTRATION_CONNECTION_UK unique (CONNECTIONSETTING),
	constraint ORCHESTRATION_CONNECTION_PK primary key (ID)
);
